<a href="https://colab.research.google.com/github/23024chensimng/collar_GPU/blob/main/%E6%95%B0%E6%8D%AE%E9%A2%84%E5%A4%84%E7%90%86.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 数据预处理，CSV

In [ ]:
import os
import pandas
os.makedirs(os.path.join('..','data'),exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [ ]:
import pandas as pd
data = pd.read_csv(data_file)
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [ ]:
inputs,outputs = data.iloc[:,0:2] , data.iloc[:,2]  #index location
inputs = inputs.fillna(inputs.mean(numeric_only=True)) #取平均值时必须要将inputs都变成数字类型
inputs #NaN is not a number

NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

In [ ]:
inputs = pd.get_dummies(inputs,dummy_na=True,dtype=float) #在NaN中用虚拟变量进行二进制编辑，dummy_na=True表示在编码时保证NaN的存储
inputs = inputs.astype(int)#格式转化，为下面转化为张量做铺垫
inputs # ? 区别 : inputs.dummy_na = False or True
#_pave if pave -> True

NumRooms  Alley_Pave  Alley_nan
0         3           1          0
1         2           0          1
2         4           0          1
3         3           0          1

In [ ]:
import torch
x,y = torch.tensor(inputs.values),torch.tensor(outputs.values)
x,y

(tensor([[3, 1, 0],
         [2, 0, 1],
         [4, 0, 1],
         [3, 0, 1]]),
 tensor([127500, 106000, 178100, 140000]))

In [ ]:
#reshape , view不改变地址
a = torch.arange(12)
b = a.reshape((3,4))
b[:] = 2
a

tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

zsh:1: command not found: invidia-smi
